---
grails:
    profile: rest-api
    codegen:
        defaultPackage: sifmoz.backend
    cors:
        enabled: true
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

server:
    port:
        8884

quartz:
    autoStartup: true
    jdbcStore: false

environments:
    test:
    quartz:
        autoStartup: false
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
                - application/json
                - text/json
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 900000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    databinding:
        dateFormats:
            - "yyyy-MM-dd'T'HH:mm:ss.SSSX"
            - "yyyy-MM-dd'T'HH:mm:ss"
            - "yyyy-MM-dd"
---
micronaut:
    codec:
        json:
            additionalTypes:
                - text/javascript
---
hibernate:
    enable_lazy_load_no_trans: true
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:2345/coalane_migrated
        dataSources:
            second:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                driverClassName: org.postgresql.Driver
                dbCreate: update
                url: jdbc:postgresql://localhost:2345/coalane
                hibernate:
                    readOnly: true
    test:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/idmed
    production:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://db:5432/idmed
        dataSources:
            second:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                driverClassName: org.postgresql.Driver
                dbCreate: update
                url: jdbc:postgresql://db:5432/idmedusada
                hibernate:
                    readOnly: true
